// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTQ_K1lKdP01_PbCYAY4zS6nDM1UKZAOE',
    appId: '1:518516969082:web:1cbf17f5ee6188b67575c3',
    messagingSenderId: '518516969082',
    projectId: 'producao-chopp',
    authDomain: 'producao-chopp.firebaseapp.com',
    storageBucket: 'producao-chopp.firebasestorage.app',
    measurementId: 'G-RFMJKEQ257',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN966Wamj22w4CtYpNz1Mrr1QSayHk-rY',
    appId: '1:518516969082:android:2854779e055ddcf07575c3',
    messagingSenderId: '518516969082',
    projectId: 'producao-chopp',
    storageBucket: 'producao-chopp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOphDrZOyxv6Q7I6jbaQqP5-hurCo846Y',
    appId: '1:518516969082:ios:3145605bf93ff3b17575c3',
    messagingSenderId: '518516969082',
    projectId: 'producao-chopp',
    storageBucket: 'producao-chopp.firebasestorage.app',
    iosBundleId: 'com.santos.valdomiro.gestaoProducaoChopp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOphDrZOyxv6Q7I6jbaQqP5-hurCo846Y',
    appId: '1:518516969082:ios:3145605bf93ff3b17575c3',
    messagingSenderId: '518516969082',
    projectId: 'producao-chopp',
    storageBucket: 'producao-chopp.firebasestorage.app',
    iosBundleId: 'com.santos.valdomiro.gestaoProducaoChopp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTQ_K1lKdP01_PbCYAY4zS6nDM1UKZAOE',
    appId: '1:518516969082:web:eb109ad7d5347ae77575c3',
    messagingSenderId: '518516969082',
    projectId: 'producao-chopp',
    authDomain: 'producao-chopp.firebaseapp.com',
    storageBucket: 'producao-chopp.firebasestorage.app',
    measurementId: 'G-W779X2D74P',
  );
}
